# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    RELEASE_VERSION=v0.17.0
    curl -LO https://github.com/operator-framework/operator-sdk/releases/download/${RELEASE_VERSION}/operator-sdk-${RELEASE_VERSION}-x86_64-linux-gnu
    chmod +x operator-sdk-${RELEASE_VERSION}-x86_64-linux-gnu && sudo mkdir -p /usr/local/bin/ && sudo cp operator-sdk-${RELEASE_VERSION}-x86_64-linux-gnu /usr/local/bin/operator-sdk && rm operator-sdk-${RELEASE_VERSION}-x86_64-linux-gnu
  displayName: 'Download operator-sdk'

- script: |
    operator-sdk version
  displayName: 'Verify operator-sdk'

- script: |
    GOPATH=$PWD
    operator-sdk \
      build \
      quay.io/repository/hkaneko/gitbucket-operator:1.0-$(Build.BuildId) \
      --go-build-args "-o ./build/_output/bin/gitbucket-operator"
  displayName: 'Build Operator Image'

- task: Docker@2
  inputs:
    containerRegistry: 'Quay'
    repository: 'gitbucket-operator'
    command: 'push'
    tags: '1.0-$(Build.BuildId)'