apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: gitbuckets.gitbucket.example.io
spec:
  group: gitbucket.example.io
  names:
    kind: GitBucket
    listKind: GitBucketList
    plural: gitbuckets
    singular: gitbucket
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: GitBucket is the Schema for the gitbuckets API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: GitBucketSpec defines the desired state of GitBucket
          properties:
            enable_database:
              type: boolean
            enable_public:
              type: boolean
            gitbucketHome:
              properties:
                ephemeral:
                  type: boolean
                mount_path:
                  type: string
                size:
                  format: int32
                  type: integer
              required:
              - ephemeral
              - mount_path
              - size
              type: object
            image:
              type: string
            size:
              format: int32
              type: integer
          required:
          - enable_database
          - enable_public
          - gitbucketHome
          - image
          - size
          type: object
        status:
          description: GitBucketStatus defines the observed state of GitBucket
          properties:
            nodes:
              description: 'INSERT ADDITIONAL STATUS FIELD - define observed state
                of cluster Important: Run "operator-sdk generate k8s" to regenerate
                code after modifying this file Add custom validation using kubebuilder
                tags: https://book-v1.book.kubebuilder.io/beyond_basics/generating_crd.html'
              items:
                type: string
              type: array
          required:
          - nodes
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
