apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitbucket-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: gitbucket-operator
  template:
    metadata:
      labels:
        name: gitbucket-operator
    spec:
      serviceAccountName: gitbucket-operator
      containers:
        - name: gitbucket-operator
          # Replace this with the built image name
          image: quay.io/repository/hkaneko/gitbucket-operator:1.1
          command:
          - gitbucket-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "gitbucket-operator"
